version: '3'

services:
  solr:
    container_name: solr
    image: solr:8.3
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
      - ./startup.sh:/startup.sh:ro
    command: 
      - /startup.sh
      - ruian
    networks:
      - solr
  spring-boot:
    container_name: backend
    build: ./backend/
    image: backend/spring-boot
    ports:
      - "8080:8080"
    networks:
      - solr
    depends_on:
      - solr
volumes:
  data:
networks:
  solr:
    driver: bridge