version: '3'

services:
  solr:
    container_name: solr
    image: solr:8.3
    ports:
      - 8983:8983
    volumes:
      - data:/var/solr
      - ./coreConfig:/opt/solr/server/solr/configsets/ruianConfig:ro
    command: 
      - solr-precreate
      - ruian
      - /opt/solr/server/solr/configsets/ruianConfig
    networks:
      - solr
    healthcheck:
      test: wget --spider -q http://localhost:8983 || exit 1
      interval: 20s
      timeout: 10s
  spring-boot:
    container_name: backend
    hostname: spring-boot
    image: "ghcr.io/vojtechlunak/ruian-search/ruian-search:latest"
    environment:
      RUIAN_SOLR_URL: http://solr:8983/solr      
    ports:
      - 8080:8080
    networks:
      - solr
      - proxy
    depends_on:
      - solr
    healthcheck:
      test: wget --spider -q http://localhost:8080 || exit 1
      interval: 20s
      timeout: 10s
#  vue-app:
#    container_name: frontend
#    hostname: vue-app
#    build: ./frontend/
#    image: frontend/vue
#    ports:
#      - 8000:80
#    networks:
#      - proxy
#    depends_on:
#      - spring-boot
#    healthcheck:
#      test: wget --spider -q http://localhost:80 || exit 1
#      interval: 20s
#      timeout: 10s
volumes:
  data:
networks:
  solr:
    driver: bridge
  proxy:
    driver: bridge
    