version: '3'

services:
  solr:
    container_name: solr
    image: solr:8.3
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command: 
      - solr-precreate # Create core and name it ruian
      - ruian
volumes:
  data: