version: '3'

services:
  solr:
    container_name: solr
    image: solr:8.3
    volumes:
      - data:/var/solr
      - ./coreConfig:/opt/solr/server/solr/configsets/ruianConfig:ro
    command: 
      - solr-precreate
      - ruian
      - /opt/solr/server/solr/configsets/ruianConfig
    networks:
      - solr
    healthcheck:
      test: wget --spider -q http://localhost:8983 || exit 1
      interval: 20s
      timeout: 10s
  spring-boot:
    container_name: backend
    hostname: spring-boot
    build:
      context: ./backend/
      args:
        RUIAN_SOLR_URL: http://solr:8983/solr
    image: backend/spring-boot
    environment:
      RUIAN_SOLR_URL: http://solr:8983/solr      
    networks:
      - solr
      - proxy
    depends_on:
      - solr
    healthcheck:
      test: wget --spider -q http://localhost:8080 || exit 1
      interval: 20s
      timeout: 10s
  vue-app:
    container_name: frontend
    hostname: vue-app
    build: ./frontend/
    image: frontend/vue
    networks:
      - proxy
    depends_on: 
      - spring-boot
    healthcheck:
      test: wget --spider -q http://localhost:80 || exit 1
      interval: 20s
      timeout: 10s
  proxy:
    container_name: proxy
    image: nginx:1.17-alpine
    ports:
      - 8000:80
    networks:
      - proxy
    volumes:
      - ./nginxConfig:/etc/nginx
    depends_on:
      - vue-app
volumes:
  data:
networks:
  solr:
    driver: bridge
  proxy:
    driver: bridge
    